[build]
target = "avr-atmega328p.json"
# target = "avr-unknown-gnu-atmega328"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600 -P /dev/ttyACM0"

# [target.'cfg(all(target_arch = "avr"))']
# runner = "simavr -m atmega328p"


[unstable]
build-std = ["core"]
# this is a fix to allow floating point operations to work
build-std-features = ["compiler-builtins-mangled-names"]